### PR TITLE
Add logomark to the bottom-center of the plymouth splash.

### LINKED ISSUE #18: Bring back the elementary logo
### Problem

My understanding is that the elementary logo was removed so that the device vendor uefi logo would be more prominent during boot.

But this change made me sad.

### Proposal

Bring back the elementary logo but similar to what other distributions do which is the vendor logo in the middle of the screen, the spinner as it is currently, and a small elementary logo near the bottom.

### Prior Art (Optional)

Other distributions' Plymouth splash screens such as Ubuntu, Fedora, openSUSE.

### PR DESCRIPTION
**Pull request by vjr**
Fixes #18

### CODE REVIEW

**Comment by vjr** [comment]
Screenshot:

image

**Comment by vjr** [comment]
Hi folks!

What do you think of the following look to the plymouth splash?

See:

https://youtube.com/shorts/Der0BpirjYc

**Comment by SubhadeepJasu** [comment]
Concept arts involved in making of this:
Frame 2
Frame 5
Frame 6

**Comment by danirabbit** [comment]
This feels really busy to me and I kind of want to get away from the current logotype. I don't feel like it pairs well with the logomark.

One thing that was previously floating was using a "+" symbol between the two logos as in:
bitmap

**Comment by jlnr** [comment]
The + looks nice, but to me it intuitively suggests an official partnership between Dell and elementary.

(Also, not every boot logo is as nice and uniform as Dell's, to put it mildly.)

**Comment by vjr** [comment]
Thanks folks for your comments - I've switched to just using the logomark instead of the logotype for the plymouth watermark positioned at the bottom-center to keep things simple. What do you think of it now?

**Comment by danirabbit** [comment]
Hey sorry for taking so long to follow up here. Another option which I don't why I didn't think of sooner is to do like video games and old game consoles did and fade between the logos. So my suggestion would be to show the OEM logo first and then crossfade to the elementary e logo. This way we get both logos but it's not cluttered and it's a pattern we've seen before in other places with Gameboy for example where you get the hardware logo first then the software logo and then you're in there

**Comment by SubhadeepJasu** [comment]
I like the idea. I can prepare an animation for it.

**Comment by SubhadeepJasu** [comment]
I prepared this animation, but one thing does bother me. In most laptops nowadays, elementary boots really really fast. 
But having an animation like this would mean intentionally slowing it down (or waiting), at least until the intro frames are rendered. It's the same if you two fade outs between two logos. Also in some UEFI  setups, the OEM logo appears right at the beginning and then a "blink" and then the OS loading spinner appears. 

https://github.com/elementary/plymouth-theme/assets/20795161/5a82d397-d4aa-4514-8aec-0f61b147e513

**Comment by vjr** [comment]
Hi folks - just to take a step back - see my comment here: https://github.com/elementary/plymouth-theme/issues/18#issuecomment-1745334950

Latest state of this PR: https://github.com/elementary/plymouth-theme/pull/20/commits/624fa0ad214df745cf9449216c7eaf22ea75085f

Essentially - no fancy stuff/effort for now - thanks for your mockups though! - intent is to only add the logomark as a first step...

**Comment by vjr** [comment]
> Hi folks - just to take a step back - see my comment here: [#18 (comment)](https://github.com/elementary/plymouth-theme/issues/18#issuecomment-1745334950)
> 
> Latest state of this PR: [624fa0a](https://github.com/elementary/plymouth-theme/commit/624fa0ad214df745cf9449216c7eaf22ea75085f)
> 
> Essentially - no fancy stuff/effort for now - thanks for your mockups though! - intent is to only add the logomark as a first step...

@elementary/desktop-developers requesting re-review (just add a logomark for now, no animations) for inclusion in OS 8 or even 7.1 since it's a trivial change, pending approval from @elementary/ux

**Review by lenemter — APPROVED** [review]

**Review by danirabbit — CHANGES_REQUESTED** [review]
I'd prefer not to have multiple logos on screen at one time

**Comment by vjr** [comment]
Not even if it's the logotype instead of the logomark, like how some of the other distros are doing? (at least I know Fedora and Tumbleweed do this).

Anyway, I'll close this PR for the time being - I don't know the way to do (code wise) a cross fade between vendor logo and elementary logo (as asked here: https://github.com/elementary/plymouth-theme/pull/20#issuecomment-1726693317) so will leave the issue ticket open if someone else wants to give it a shot.

**Comment by danirabbit** [comment]
I'd really like to get away from the current logotype completely tbh 😅

**Comment by vjr** [comment]
Yeah :-) I just grabbed the logotype from the brand assets IIRC (of course) so it's just a matter of replacing one file with whatever new logotype you folks design, that could be crossfaded with the vendor logo.

**Pull request closed without merging**
