### PR TITLE
Use same background as greeter

### PR DESCRIPTION
**Pull request by meisenzahl**
Closes https://github.com/elementary/plymouth-theme/issues/1

Bildschirmfoto von 2020-11-14 07-53-07

Bildschirmfoto von 2020-11-14 07-53-12

### CODE REVIEW

**Comment by meisenzahl** [comment]
Unfortunately, I just had to realize that this does not work if you connect your laptop to a monitor with a higher resolution 😒
Since `Window.GetWidth ()` and `Window.GetHeight ()` can return the values from the laptop.

From my point of view there are 3 possible solutions:

<details><summary>Solid gray background</summary>

####
<pre>
<code>
# set solid gray background #2e3436
# https://github.com/elementary/greeter/blob/931d001998cf207a079516d99b0852f90d3568df/compositor/SystemBackground.vala#L27
# R: #2e ->  46 -> 0.180392
# G: #34 ->  52 -> 0.203922
# B: #36 ->  54 -> 0.211765
Window.SetBackgroundTopColor (0.180392, 0.203922, 0.211765);     # Nice colour on top of the screen fading to
Window.SetBackgroundBottomColor (0.180392, 0.203922, 0.211765);  # an equally nice colour on the bottom
</code>
</pre>
</details>

<details><summary>Texture with solid gray background as fallback</summary>

####
<pre>
<code>
# set solid gray background #2e3436
# https://github.com/elementary/greeter/blob/931d001998cf207a079516d99b0852f90d3568df/compositor/SystemBackground.vala#L27
# R: #2e ->  46 -> 0.180392
# G: #34 ->  52 -> 0.203922
# B: #36 ->  54 -> 0.211765
Window.SetBackgroundTopColor (0.180392, 0.203922, 0.211765);     # Nice colour on top of the screen fading to
Window.SetBackgroundBottomColor (0.180392, 0.203922, 0.211765);  # an equally nice colour on the bottom

texture = Image("texture.png");
background = [];

# Fill background with texture
index = 0;
for (row = 0; (row * texture.GetHeight ()) < Window.GetHeight (); row++) {
    for (column = 0; (column * texture.GetWidth ()) < Window.GetWidth (); column++) {
        background[index] = Sprite ();
        background[index].SetImage (texture);
        background[index].SetPosition (column * texture.GetWidth (), row * texture.GetHeight (), 0);
        index++;
    }
}
</code>
</pre>
</details>

<details><summary>Define maximum default values</summary>

####
<pre>
<code>
texture = Image("texture.png");
background = [];

max_width = 4096;
max_height = 2160;

# Fill background with texture
index = 0;
for (row = 0; (row * texture.GetHeight ()) < max_height; row++) {
    for (column = 0; (column * texture.GetWidth ()) < max_width; column++) {
        background[index] = Sprite ();
        background[index].SetImage (texture);
        background[index].SetPosition (column * texture.GetWidth (), row * texture.GetHeight (), 0);
        index++;
    }
}
</code>
</pre>
</details>

**Comment by cassidyjames** [comment]
@meisenzahl is there any significant downside to a combination of the last two options? i.e. fill a default 4K size with the texture, then anything outside of that would get solid gray?

**Comment by meisenzahl** [comment]
@cassidyjames no, there are no performance issues. Even on my cheap laptop:

CPU: Intel Pentium N4200
GPU: Intel HD Graphics 505

**Comment by cassidyjames** [comment]
@meisenzahl how do I build/test this? :sweat_smile:

**Comment by meisenzahl** [comment]
@cassidyjames 

## With reboot

```
sudo cp -r elementary/* /usr/share/plymouth/themes/elementary/
sudo update-initramfs -u -k all
```

and reboot

## Without reboot

I think you need `plymouth-x11`.

```
sudo cp -r elementary/* /usr/share/plymouth/themes/elementary/
sudo update-initramfs -u -k all
```

Plymouth draws over your desktop like in the screenshots above. Please be aware that you need Terminal 2 on another workspace to close Plymouth.

### Terminal 1

#### Tab 1

Start Plymouth daemon

```
sudo plymouthd --no-daemon --debug
```

#### Tab 2

Show splash

```
sudo plymouth show-splash
```

### Terminal 2

Close Plymouth

```
sudo plymouth quit
```

**Comment by cassidyjames** [comment]
@meisenzahl hm…

I like this better at a glance, but I wonder if it conflicts with https://github.com/elementary/os/issues/367?

It might make more sense to just show whatever an OEM has and a minimal loading bar or something (if even that).

**Comment by meisenzahl** [comment]
@cassidyjames yeah it could conflict with https://github.com/elementary/os/issues/367 because of the black background most OEMs use in their UEFI logo.

I should have expressed my concerns more clearly in https://github.com/elementary/os/issues/367:

> I'm just afraid that we then have to decide if we want to have a completely black background or one that fits the greeter: elementary/plymouth-theme#1

**Comment by cassidyjames** [comment]
@meisenzahl yeah the more I am thinking about this, the more I think we just do a black screen and show the OEM logo if it is there. I am not exactly sure how sizing/positioning that works, but I recall the Ubuntu bgrt theme seemed to put the image where I would expect on a few different OEM machines.

#1 is a decent idea but if we don't expect this screen to be up for long, AND we want to support OEM logos, I think black makes sense.

Sorry if any of this was a waste of your time!

**Pull request closed without merging**
